<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
.collapsible {
  background-color: #777;
  color: white;
  cursor: pointer;
  padding: 18px;
  width: 100%;
  border: none;
  text-align: left;
  outline: none;
  font-size: 15px;
}

.active, .collapsible:hover {
  background-color: #555;
}

.content {
  padding: 0 18px;
  max-height: 0;
  overflow: hidden;
  transition: max-height 0.2s ease-out;
  background-color: #f1f1f1;
  color: black;
}

<style>
a:link {
  color: blue;
  background-color: transparent;
  text-decoration: none;
}
a:visited {
  color: blue;
  background-color: transparent;
  text-decoration: none;
}
a:hover {
  color: red;
  background-color: transparent;
  text-decoration: underline;
}
a:active {
  color: red;
  background-color: transparent;
  text-decoration: underline;
}
</style>

</style>

<title>Material for the Manchester course 2023</title>

## The NCRM Summer School in Manchester July 11-14, 2023 (funded by ESRC)

<br />
<br />

### The full set of material for this course
<ul>
    <li><button type="button" class="btn btn-primary">[Notes for lectures 1 to 5](data/courses/Man2023/lectures_1to5.zip)</button></li>
    <li><button type="button" class="btn btn-primary">[Notes for lectures 6 to 7](data/courses/Man2023/lectures_6to7.zip)</button></li>
    <li><button type="button" class="btn btn-primary">[Practicals 1 to 7](data/courses/Man2023/practicals.zip)</button></li>
</ul>

<br />

### Preparatory material
<br />

<p> Below is a set of material to prepare your laptop and yourself prior to attending the NCRM Summer school in Manchester July 11-14, 2023. If you have any problems, please contact Philip at guangquan.li@northumbria.ac.uk. We look forward to meeting everyone in Manchester soon.</p>

<br />

### 1. Installing R, RStudio and WinBUGS

<button class="collapsible">- Installing R</button>
<div class="content">
<p>Both R and RStudio need to be installed to correctly run RStudio. R can be considered as the programming language being used, whilst RStudio is a more user-friendly platform for coding. 
R can be installed from [www.r-project.org](https://r-project.org), by clicking the ‘download R’ link, you can then select either of the UK CRAN mirrors (University of Bristol or Imperial College London). </p>

<p>You must then select the operating system you are using, i.e. Windows, macOS, by clicking ‘Download R for XX’ where XX is your chosen system. You can then select the version of R you want to install. For Windows users, please download the base version.  For macOS users, please install the R version depending on your processor (M1/M2/intel). </p>
</div>

<button class="collapsible">- Installing RStudio</button>
<div class="content">
<p>RStudio can be installed from [www.posit.co/products/open-source/rstudio](https://posit.co/products/open-source/rstudio), and by clicking ‘Download RStudio’ in the top right corner. Then, after making sure the ‘RStudio Desktop’ tab is highlighted, click the download button inside the RStudio Desktop (Free) box. </p>

<p>From this page you can scroll down to find the correct version for the operating system you are using, and click to download RStudio. </p>

<p>If you have not use R/RStudio before, [this one-page introduction](https://mathcenter.oxford.emory.edu/site/math117/firstUseOfRStudio/) will help to start your R journey.</p>

</div>

<button class="collapsible">- Installing packages in R</button>
<div class="content">
<p> Throughout the course, we will be using a number of packages in R to carry out specific analyses. We can use the <code>install.packages</code> function to install a package. So by running the code <code>install.packages('maptools')</code> in R, we install the <code>maptools</code> package which we will use for manipulating a shapefile, a digital version of a map. We would like you to install the following packages:</p>
<ul>
  <li> <code>maptools</code>
  <li> <code>R2WinBUGS</code> (note: R is case sensitive)
  <li> <code>spdep</code>
  <li> <code>RColorBrewer</code>
</ul>

<p> In the future, when running a set of code, if R returns an error message saying a package is not found, you can use the <code>install.packages</code> function to install it (then run the code again).</p>
</div>


<button class="collapsible">- Installing WinBUGS</button>
<div class="content">
<p>For macOS and Linux users: please contact guangquan.li@northumbria.ac.uk for installation detail.</p>

<p>For Windows users: WinBUGS can be installed from [www.mrc-bsu.cam.ac.uk/software/bugs/the-bugs-project-winbugs/](https://www.mrc-bsu.cam.ac.uk/software/bugs/the-bugs-project-winbugs/). A .zip file can be downloaded by clicking the ‘Download WinBUGS’ link. Unzip the downloaded file WinBUGS14.zip and you will have a new folder called <code>winbugs14_full_patched</code>. Within that folder, go to <code>WinBUGS14/WinBUGS14.exe</code>. Double click on that file will start the program.</p>

<p> Throughout the course, we will learn how to use WinBUGS to fit Bayesian spatial and spatial-temporal models.</p>
</div>


<br />

### 2. On mapping
<button class="collapsible">- Creating a geodatabase in R </button>
<div class="content">
<p> Mapping is an important aspect in the analysis of spatial and spatial-temporal data. Before we can create a map of some spatial data, we need to create a geodatabase that contains the digital version of the geographic features (e.g. points and polygons) and the data values associated with the features. </p>

<p>Appendix 4.13.1 in our book illustrates the steps involved in creating such a database in R using a toy example. [Click here to download the contents](data/courses/Man2023/geodatabase.zip) then follow the example. We will use these steps again in the course when analysing new datasets.</p>

<p> <b>For mac users</b>: on p. 108, instead of creating the folder on the <code>C</code> drive, you create the folder with the name <code>sptmbook</code> on your Desktop. Then on Line 1 in the textbox on p. 108, instead of <code>setwd('c:/sptmbook/')</code>, you type <code>setwd('~/Desktop/sptmbook/')</code> with a capital D in Desktop. Everything else follows. Hereafter, if you see any reference to the C drive (e.g. <code>C:/sptmbook/</code>), use <code>~/Desktop/sptmbook/</code> instead.
</div>


<button class="collapsible">- Producing a choropleth map in R </button>
<div class="content">
<p> 
A choropleth map uses different colours (or different shades of a colour) to represent the values associated with the geographic features (points or areas). Section 6.2.1 in our book guides you through the steps to create a choropleth map in R. </p>

<p> [Download the material here](data/courses/Man2023/mapping.zip) (a zip file called <code>mapping.zip</code>) and move the zip file to the folder <code>C:/sptmbook/</code> (or <code>~/Desktop/sptmbook/</code> for mac users) the one that you created for the exercise on creating a geodatabase (complete the exercise on Creating a geodatabase in R now if you have not done so). Unzip the file and you will have a folder called <code>mapping</code>. Unzip the file <code>cambridgeship.zip</code> in the folder <code>mapping</code>. Follow the instructions in the pdf file <code>mapping.pdf</code>. Prior to running the R code in the textbox on p. 162, set your working directory by entering the following line in R <code>setwd('c:/sptmbook/mapping/cambridgeshire')</code>. You are now ready to run through the steps in the pdf.
</p>

</div>


<br />

### 3. On creating the weights matrix + accessing data from a shapefile

<button class="collapsible">- Creating the weights matrix </button>
<div class="content">
<p> The spatial weights matrix (also known as the W matrix), as we shall discuss in the course, is an important element in modelling spatial and space-time data. We construct the W matrix to quantify the spatial relationships amongst a set of areas (or points) within the study region. </p>

<p>This set of material ([click here to download](data/courses/Man2023/weights_matrix.zip)) shows how to construct a W matrix based on contiguity. First read through the pdf file called <code>weights_matrix.pdf</code>) to understand what a weights matrix is and what contiguity means then go through Appendix 4.13.2 (in the pdf file called <code>construct_w_matrix.pdf</code>) to construct a weights matrix based on the shapefile you constructed under the Creating a geodatabase in R task (see Point 2 above).</p>

</div>

<button class="collapsible">- Extracting data from a shapefile </button>
<div class="content">
<p> p. 112-113 in Appendix 4.13.2 (in <code>construct_w_matrix.pdf</code> above) shows how to extract relevant data from a shapefile for mapping and/or analysis. You would also have done this in the mapping exercise.</p>

</div>

<br />



<script>
var coll = document.getElementsByClassName("collapsible");
var i;

for (i = 0; i < coll.length; i++) {
  coll[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var content = this.nextElementSibling;
    if (content.style.maxHeight){
      content.style.maxHeight = null;
    } else {
      content.style.maxHeight = content.scrollHeight + "px";
    } 
  });
}
</script>

