<title>News </title>

<br />

### A 3.5 days course on modelling spatial and spatial-temporal data

___

Following the publication of our book, we will be delivering a training course on modelling spatial and spatial-temporal data. This training course introduces powerful Bayesian spatial and spatial-temporal modelling techniques that enable researchers to analyse social, economic, political and public health data.


<br />

#### <u>When and where</u>

~~April 5-8, 2022 at Northumbria University, UK.~~

Unfortunately, we have to postpone the course due to insufficient numbers. We are planning to organise the course again later in the year. If you are interested in attending, please register your interest via the link above. You will be put on a mailing list and will be contacted once the plan is in place. 

<br />
<button type="button" class="btn btn-primary">[Please register your interest here](https://www.northumbria.ac.uk/study-at-northumbria/continuing-professional-development-short-courses-specialist-training/spatial-and-spatial-temporal-data-analysis-using-bayesian-hierarchical-models/)</button>


<br />

#### <u>Course leaders</u>

Prof. Robert Haining (University of Cambridge) and Dr. Guangquan Li (Northumbria University)

<br />

#### <u>Course outline</u>
* Types and properties of spatial and spatial-temporal data and implications for model building;
* Techniques for testing spatial heterogeneity and autocorrelation; clusters and hotspot detection;
* Uses of maps and graphics for visualization using R;
* Bayesian inference for spatial and spatial-temporal data;
* Introduction to Markov chain Monte Carlo methods;
* Simple Bayesian regression models;
* Bayesian hierarchical models for spatial data, both continuous (e.g., normal/log normal data) and discrete (e.g., count/binary data);
* Implementation of various Bayesian hierarchical models in WinBUGS for spatial data;
* Introduction to spatial econometric models;
* Regression diagnostics with particular relevance for spatial data;
* Introduction to modelling small area time series data, including linear models in time, autoregressive models and interrupted time series models;
* Introduction to various strategies/structures for modelling spatial-temporal data;
* Discussion of space-time models using practical examples.

<br />

#### <u>Entry requirements</u>

The course is aimed at PhD students, Post-Doctoral researchers and academic staff in the social, economic, political and public health sciences who have a background in quantitative methods at least up to and including the normal linear regression model. Prior experience of generalized linear modelling will be helpful for some parts of the course as will some familiarity with the basic ideas behind Bayesian inference.

